export const designRouteMap = [
  { designFolder: 'splash_screen', route: '/splash', status: 'implemented' },
  { designFolder: 'onboarding_1', route: '/onboarding/step-1', status: 'implemented' },
  { designFolder: 'onboarding_2', route: '/onboarding/step-2', status: 'implemented' },
  { designFolder: 'onboarding_3', route: '/onboarding/step-3', status: 'implemented' },
  { designFolder: 'ng_nh_p_ng_k', route: '/auth/login', status: 'implemented' },
  { designFolder: 'x_c_th_c_otp', route: '/auth/otp', status: 'implemented' },
  { designFolder: 'qu_n_m_t_kh_u', route: '/auth/forgot-password', status: 'route-mapped' },
  { designFolder: 'ng_k_t_i_kho_n_1', route: '/auth/register/step-1', status: 'implemented' },
  { designFolder: 'ng_k_t_i_kho_n_2', route: '/auth/register/step-2', status: 'implemented' },
  { designFolder: 'profile_setup_1_4', route: '/profile-setup/step-1', status: 'route-mapped' },
  { designFolder: 'profile_setup_2_4', route: '/profile-setup/step-2', status: 'route-mapped' },
  { designFolder: 'profile_setup_3_4', route: '/profile-setup/step-3', status: 'route-mapped' },
  { designFolder: 'profile_setup_4_4', route: '/profile-setup/step-4', status: 'route-mapped' },
  { designFolder: 'home_dashboard_chi_ti_t', route: '/dashboard/detail', status: 'route-mapped' },
  { designFolder: 'l_ch_tr_nh_th_ng_monthly_plan', route: '/plans/monthly', status: 'route-mapped' },
  { designFolder: 'l_ch_tr_nh_tu_n', route: '/plans/weekly', status: 'route-mapped' },
  { designFolder: 'result_screen_updated', route: '/results/summary', status: 'route-mapped' },
  { designFolder: 'emerald_vitality', route: '/features/emerald-vitality', status: 'route-mapped' },
] as const;
