export const ROUTES = {
  splash: '/splash',
  onboarding1: '/onboarding/step-1',
  onboarding2: '/onboarding/step-2',
  onboarding3: '/onboarding/step-3',
  login: '/auth/login',
  phoneLogin: '/auth/phone',
  registerStep1: '/auth/register/step-1',
  registerStep2: '/auth/register/step-2',
  otp: '/auth/otp',
  forgotPassword: '/auth/forgot-password',
  profileSetup1: '/profile-setup/step-1',
  profileSetup2: '/profile-setup/step-2',
  profileSetup3: '/profile-setup/step-3',
  profileSetup4: '/profile-setup/step-4',
  dashboard: '/(tabs)',
  dashboardDetail: '/dashboard/detail',
  monthlyPlan: '/plans/monthly',
  weeklyPlan: '/plans/weekly',
  result: '/results/summary',
  emeraldVitality: '/features/emerald-vitality',
} as const;
